package com.threabba.android.pedometer.db;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "RECORD".
 */
@Entity
public class Record implements Parcelable{

    @Id
    private Long id;

    @NotNull
    private java.util.Date date;
    private int step_count;
    private float distance;

    @Generated
    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    @Generated
    public Record(Long id, java.util.Date date, int step_count, float distance) {
        this.id = id;
        this.date = date;
        this.step_count = step_count;
        this.distance = distance;
    }

    protected Record(Parcel in) {
        step_count = in.readInt();
        distance = in.readFloat();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(step_count);
        dest.writeFloat(distance);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<Record> CREATOR = new Creator<Record>() {
        @Override
        public Record createFromParcel(Parcel in) {
            return new Record(in);
        }

        @Override
        public Record[] newArray(int size) {
            return new Record[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(@NotNull java.util.Date date) {
        this.date = date;
    }

    public int getStep_count() {
        return step_count;
    }

    public void setStep_count(int step_count) {
        this.step_count = step_count;
    }

    public float getDistance() {
        return distance;
    }

    public void setDistance(float distance) {
        this.distance = distance;
    }

}
